### ISSUE TITLE
Docker local host faliure

### ISSUE THREAD

**Issue by Himscipy** [SenHuang19/BuildingControlEmulator#2]
Hi,

Using following instructions, [Methodology](https://building-control-emulator.readthedocs.io/en/latest/buildingEmulatorExamples.html) instruction step-6 returns following error.
```
SIMULATION SETUP INFORMATION
---------------------
Traceback (most recent call last):
  File "/Users/shar306/Work/PACKAGES/miniconda3/lib/python3.7/site-packages/urllib3/connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/Users/shar306/Work/PACKAGES/miniconda3/lib/python3.7/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/Users/shar306/Work/PACKAGES/miniconda3/lib/python3.7/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/shar306/Work/PACKAGES/miniconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/Users/shar306/Work/PACKAGES/miniconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Users/shar306/Work/PACKAGES/miniconda3/lib/python3.7/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/shar306/Work/PACKAGES/miniconda3/lib/python3.7/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/shar306/Work/PACKAGES/miniconda3/lib/python3.7/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/shar306/Work/PACKAGES/miniconda3/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/Users/shar306/Work/PACKAGES/miniconda3/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/Users/shar306/Work/PACKAGES/miniconda3/lib/python3.7/site-packages/urllib3/connection.py", line 184, in connect
    conn = self._new_conn()
  File "/Users/shar306/Work/PACKAGES/miniconda3/lib/python3.7/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x10ade4c90>: Failed to establish a new connection: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/shar306/Work/PACKAGES/miniconda3/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Users/shar306/Work/PACKAGES/miniconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/Users/shar306/Work/PACKAGES/miniconda3/lib/python3.7/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='0.0.0.0', port=5000): Max retries exceeded with url: /name (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10ade4c90>: Failed to establish a new connection: [Errno 61] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "runSimulation.py", line 138, in <module>
    main(sys.argv[1:])
  File "runSimulation.py", line 62, in main
    name = requests.get('{0}/name'.format(url)).json()
  File "/Users/shar306/Work/PACKAGES/miniconda3/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/shar306/Work/PACKAGES/miniconda3/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/shar306/Work/PACKAGES/miniconda3/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/shar306/Work/PACKAGES/miniconda3/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Users/shar306/Work/PACKAGES/miniconda3/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='0.0.0.0', port=5000): Max retries exceeded with url: /name (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10ade4c90>: Failed to establish a new connection: [Errno 61] Connection refused'))
```

I tried using two python environment on MacOS. 
1) Conda Install Python3
2) OS installed Python3

Both resulted in the above error. Further, by executing "docker -info" the "127.0.0.1/8" was pointed as an insecure registry.

**Comment by Himscipy** [comment]
Hello, 

I looked further into the docker instantiation command provide in documentations. The issue is in the `--network=host` if this is passed as argument the `-p` option is overwritten and is not used according to [docker documentation](https://docs.docker.com/network/host/).  Therefore the correct command for docker initialization should be;

```
docker run -it --rm -p="5000:5000" --mount type=bind,source=/<path>/<to>/<the>/adaptive-control-with-julia-1/emulatorExamples,destination=/mnt/emulator --name=building_control_emulator laurmarinovici/building_control_emulator bash
```
Next the [step-6](https://building-control-emulator.readthedocs.io/en/latest/buildingEmulatorExamples.html) shown in the document can run successfully to run the simulation to produce following output;

```
SIMULATION SETUP INFORMATION
---------------------
Name:				wrapped
Default Simulation Step:	60.0
Resetting simulation to start in a certain day of year at a certain time in seconds.
Setting simulation step to 300.
============ Started running simulation ============

Simulated step 1.
Current time 17280300.0 seconds.

Simulated step 2.
Current time 17280600.0 seconds.

Simulated step 3.
Current time 17280900.0 seconds.

Simulated step 4.
Current time 17281200.0 seconds.

============= Simulation complete. =================
```

I am closing the issue here...!! Thanks.
